# Generated by Django 4.1.3 on 2023-01-15 22:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CrearMensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emisor', models.CharField(default='...', max_length=30)),
                ('receptor', models.CharField(max_length=30)),
                ('cuerpo', models.CharField(max_length=50)),
                ('leido', models.CharField(choices=[('NO', 'no'), ('SI', 'si')], default='NO', max_length=10)),
                ('fechaEnvio', models.DateTimeField()),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
